### ISSUE TITLE
Add delete button for each todo item

### ISSUE THREAD

**Issue by shreyaraj13** [ayushmann01/todo-list#1]
It's a good to-do app one can add a to-do item and strike it off if the task is done, but it will be great if there is a delete button on each to-do item. It will be helpful if one wants to delete the list item.

**Comment by ayushmann01** [comment]
Thanks for your review Shreya. Instead of deleting one item now, we can delete the whole list once all the tasks are completed or we can just strike off the inappropriate tasks for now.
